# https://docs.netlify.com/routing/redirects/rewrites-proxies/
[[redirects]]
  from = "/api/*"
  # https://docs.netlify.com/routing/redirects/redirect-options/#splats
  to = "https://jingwei.app.studio.crazydan.org/app/api/diandi/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  #signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
